// Command saguin runs the broker.
package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	_ "embed"
	"errors"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/signal"
	"path/filepath"
	"runtime/debug"
	"sort"
	"strings"
	"sync/atomic"
	"syscall"
	"time"

	"github.com/ifnesi/saguin/internal/mqtt/listeners"

	"github.com/ifnesi/saguin/internal/bridge"
	"github.com/ifnesi/saguin/internal/broker"
	"github.com/ifnesi/saguin/internal/channel"
	"github.com/ifnesi/saguin/internal/config"
	"github.com/ifnesi/saguin/internal/proxyproto"
	"github.com/ifnesi/saguin/internal/store"
	"github.com/ifnesi/saguin/internal/store/sqlite"
)

// notices is the attribution that travels inside the binary, generated by
// `make notices` from the modules that reach it. saguin ships as one file,
// so a recipient has no go.mod to read and --licenses is the only place
// they can learn whose code is in there.
//
// Embedded rather than restated in Go, because two copies of a licence list
// drift and the one nobody prints is the one that goes wrong.
//
//go:embed THIRD-PARTY-NOTICES.md
var notices string

// heapFloor is a fixed minimum-heap allowance: memory the collector counts
// as live, so that it lets a small heap grow by at least that much garbage
// before collecting again (saguin). Go collects once the heap has grown by
// GOGC percent of what was live at the last collection, goroutine stacks and
// globals included. A broker holding few connections has a small live heap,
// so it collected often: at 200 connections and 10,000 QoS 1 messages a
// second the live heap was 2 MB, and the collector ran 46 times a second and
// took a fifth of the broker's CPU. Every collection also halves the stacks
// of readers parked between packets, which grow back on the next one. With
// 8 MB it ran 7 times a second and a message cost 19% less CPU; at 1,000
// connections, 9% less. At 10,000 the live heap is large enough that the
// floor changes little. 8 MB is the knee of a sweep of 0 to 32: 4 got half
// to two thirds of the gain, 16 and 32 little more than 8.
//
// **What it costs**: about 1 MB resident at rest, none of it the floor's own
// pages, and up to 10 MB under load, the extra garbage a later collection
// lets build up. It holds no pointers, so the collector never scans it, and
// nothing writes it, so the kernel never backs its pages
// (TestTheHeapFloorIsLivePointerFreeAndUntouched).
//
// **The Go runtime's own memory figures count it**, though the process's
// resident memory does not: runtime/metrics, runtime.MemStats and a heap
// profile show it as live, allocated by this package's init. It counts toward
// an operator's GOMEMLIMIT, so under a tight limit collection comes sooner,
// not later. GOMEMLIMIT only caps the collector's target and is no way to
// raise it; the alternatives are a higher GOGC, whose cost grows with the
// whole live heap, or GOGC=off with a GOMEMLIMIT (RFC 0005, "The runtime's
// own pauses, and the two variables that move them").
var heapFloor = withoutHugePages(make([]byte, heapFloorSize))

// heapFloorSize is heapFloor's size.
const heapFloorSize = 8 << 20

// snapshotLockName is the file a broker holds in a snapshot directory. It
// cannot collide with a channel's file: a channel name reaches a file name
// with everything outside a small safe set percent-encoded, so none of them
// can produce a literal dot before an extension.
const snapshotLockName = "saguin.lock"

// inUse is the set of storage providers at least one channel names.
//
// A provider nothing names is left entirely alone: declaring one must not
// create a database or a directory, and must not take a lock on either.
// Configuration describes what a broker may use, and it is a channel naming
// a provider that makes it real.
//
// It is not an error to declare one, because staging a move needs it. An
// operator converting a channel from snapshots to a database defines the
// destination provider, stops the broker, runs the migration into a path
// that does not exist yet, and only then points the channel at it. A broker
// that created the file first would leave the migration nothing to write
// into, since it refuses to write into a file that is already there.
//
// A queue's dead-letter channel needs no special case: it is an ordinary
// channel in the registry and inherits the queue's provider.
func inUse(reg *channel.Registry, alsoUsed ...string) map[string]bool {
	used := map[string]bool{}
	for _, c := range reg.All() {
		used[c.Storage] = true
	}
	// The retained store and the sessions each name a provider and neither is
	// a channel, so a provider only one of them names is in use like any
	// other. Without this the database is never opened and the store
	// silently keeps nothing.
	for _, name := range alsoUsed {
		if name != "" {
			used[name] = true
		}
	}
	return used
}

// openDatabases opens every sqlite provider a channel names and attaches a
// store to each of its channels.
//
// A channel whose provider is memory is left with the store New gave it.
//
// A queue's dead-letter channel needs no special case: it is an ordinary
// append channel in the registry, and it inherits the queue's provider, so
// the loop below opens it in the same file. That is what lets the move
// between them be one commit (invariant 5).
func openDatabases(cfg *config.File, reg *channel.Registry, b *broker.Broker, log *slog.Logger) (map[string]*sqlite.DB, error) {
	paths := cfg.Broker.Storage.SQLitePaths()
	retainedProvider, _ := cfg.RetainedStore()
	used := inUse(reg, retainedProvider, cfg.SessionStore())
	for name := range paths {
		if !used[name] {
			log.Info("storage declared and unused: nothing is created for it",
				"provider", name, "type", "sqlite", "path", paths[name])
			delete(paths, name)
		}
	}
	if len(paths) == 0 {
		return nil, nil
	}

	open := map[string]*sqlite.DB{}
	stores := broker.Stores{
		Logs:   map[string]broker.LogStore{},
		Latest: map[string]broker.LatestStore{},
		Queues: map[string]broker.QueueStore{},
	}

	// A fixed order, so that two runs of a configuration that cannot open
	// report the same provider first.
	providers := make([]string, 0, len(paths))
	for name := range paths {
		providers = append(providers, name)
	}
	sort.Strings(providers)

	closeAll := func() {
		for _, db := range open {
			_ = db.Close()
		}
	}

	bounds := cfg.Broker.Storage.MaxBytes()
	groups := cfg.Broker.Storage.CommitGroups()
	readConns := cfg.Broker.Storage.ReadConnections()
	flushEvery := cfg.Broker.Storage.FlushIntervals()
	reserve := cfg.Broker.Limits.StorageReserve()
	for _, provider := range providers {
		// A sqlite provider's ceiling is SQLite's own: it refuses the write
		// that would pass it, so nothing here counts anything.
		db, err := sqlite.OpenBoundedWithReads(paths[provider], version(), bounds[provider], reserve,
			readConns[provider])
		if err != nil {
			closeAll()
			return nil, err
		}
		open[provider] = db
		// Before any listener opens, which is the only time it may be set.
		if g, ok := groups[provider]; ok {
			db.CommitGroup(g.Interval, g.MaxRecords)
		}
		flushInterval := flushEvery[provider]
		db.SetFlushInterval(flushInterval, func(err error, first bool) {
			b.CountStorageFailure(provider, err)
			if first {
				// Once per streak: the counter has every tick.
				log.Error("the write-ahead log could not be forced to disk; acknowledged publishes since the "+
					"last successful flush may be lost to a power cut, and it is tried again every interval",
					"provider", provider, "error", err.Error())
			}
		})
		// What max_bytes actually came to. SQLite counts a file in whole
		// pages, so the operator's figure rounds down by up to one and the
		// reserve rounds up by up to one more - said here rather than left
		// to be discovered as a publish refused sooner than expected.
		publish, full, pageSize := db.Effective()
		// publish_commit_interval is said whichever way it is set, because "every
		// publish waits up to 2ms for its acknowledgement" is not something
		// an operator should have to read a configuration file to discover,
		// and neither is which of two brokers has it on.
		commitEvery, commitRecords := "behind the commit before", sqlite.BehindMaxRecords
		if g, ok := groups[provider]; ok {
			commitEvery, commitRecords = g.Interval.String(), g.MaxRecords
			if g.Interval <= 0 {
				commitEvery, commitRecords = "per publish", 0
			}
		}
		log.Info("storage opened", "provider", provider, "type", "sqlite", "path", db.Path(),
			"max_bytes", bounds[provider], "publishes_stop_at", publish,
			"reserved_for_relief", full-publish, "page_size", pageSize,
			"publish_commit_interval", commitEvery, "publish_commit_max_records", commitRecords,
			"read_connections", db.ReadConnections(), "flush_interval", flushInterval.String())
		if db.OverBound() {
			// Said once, here, rather than left for an operator to work out
			// from a broker that refuses every publish.
			log.Warn("storage already holds more than its max_bytes: publishes are refused until it is trimmed",
				"provider", provider, "path", db.Path(), "max_bytes", bounds[provider])
		}
	}

	// Sorted for the same reason, and so the log reads in a fixed order.
	names := make([]string, 0, len(reg.All()))
	for name := range reg.All() {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		c := reg.Get(name)
		db, ok := open[c.Storage]
		if !ok {
			continue
		}
		var err error
		switch c.Type {
		case channel.Append:
			stores.Logs[name], err = db.Log(name)
		case channel.Latest:
			stores.Latest[name], err = db.Latest(name)
		case channel.Queue:
			stores.Queues[name], err = db.Queue(name)
		default:
			// Unreachable while channel.Type has the three values above; a
			// fourth added without a store here is refused rather than served
			// by nothing.
			err = fmt.Errorf("channel %q: a %s channel has no sqlite store", name, c.Type)
		}
		if err != nil {
			closeAll()
			return nil, err
		}
	}
	// The providers themselves, for what a provider answers and a channel
	// cannot: a clean start forgetting one reader's positions everywhere it
	// has them, in one statement rather than one per channel.
	stores.Providers = make(map[string]broker.ReaderDropper, len(open))
	for provider, db := range open {
		stores.Providers[provider] = db
	}
	b.SetStores(stores)
	return open, nil
}

// Version is the release this code claims to be, and the only place it is
// written down. `--version`, `--help`, the startup log, saguin_build_info
// and the stamp inside every snapshot and database all come from here, so
// there is one answer to "which saguin is this".
//
// **A constant here was refused once, and the objection was the right one**:
// a version written down is wrong from the moment somebody forgets to bump
// it, and a version that lies about which code wrote a file is worse than
// none. What makes it safe is that forgetting is now a failing test rather
// than a thing to remember - TestTheVersionAgreesWithTheChangelog refuses a
// release number that no CHANGELOG.md section names, and refuses a
// changelog entry the constant has not caught up with. The build's own
// revision is still carried, appended, so the file a broker meets names
// both the release and the commit.
//
// A hyphenated suffix marks a pre-release, and the release workflow
// refuses a tag that disagrees with this constant.
const Version = "0.1.0-rc.1"

// version is Version with the build's own revision appended, and it is what
// gets stamped into every snapshot and database - so a broker meeting a
// file it cannot read can say which saguin wrote it, down to the commit.
//
// A local `go build` gives the revision and whether the tree was dirty,
// both of which the toolchain embeds on its own. A build with no repository
// behind it - `go run`, or a release archive - has neither, and says only
// what release it claims to be.
func version() string {
	bi, ok := debug.ReadBuildInfo()
	if !ok {
		return Version
	}

	var revision, modified string
	for _, s := range bi.Settings {
		switch s.Key {
		case "vcs.revision":
			revision = s.Value
		case "vcs.modified":
			if s.Value == "true" {
				modified = "-dirty"
			}
		}
	}
	if revision == "" {
		return Version
	}
	if len(revision) > 12 {
		revision = revision[:12]
	}
	// Build metadata, after a plus, which is where semantic versioning puts
	// the answer to "which build" as against "which release".
	return Version + "+" + revision + modified
}

// banner is the two lines every entry point opens with: what this is, what
// release, and under what licence.
//
// **Not in the startup log**, which is parsed. It goes to whoever typed
// --help or --version and nowhere else.
//
// **Every character was chosen for whether it renders, not for whether it
// is the prettiest.** All of them are narrow and none combines, so the two
// rows stay aligned at nine columns wherever the glyphs exist - and nothing
// here is East-Asian *ambiguous*, which would otherwise take two columns in
// a terminal configured for CJK and shift one row against the other.
//
// Counted with fontconfig on the machine this was written on: the tufts are
// in 12 and 10 monospace fonts, the eye in 12, the mouth in 8, and the rest
// is ASCII. Candidates that looked better and were dropped: Bengali
// U+09CE, in no monospace font at all, and U+269E/U+269F, in one and
// ambiguous-width besides. A reader on a bare container has fewer fonts
// than either machine, which is the argument for spending the budget here
// rather than on rarer glyphs.
func banner() string {
	return "ʚ(^ ‿ ◕)ɞ   Sagüin " + Version + "\n" +
		"~~( ‿ )     Apache-2.0 · saguin --licenses\n"
}

// listening describes the configured listeners for the startup log line,
// which is where an operator checks whether the broker opened what they
// meant it to and nothing else.
//
// **A door named after its kind is said the way it always was**, "tcp
// 0.0.0.0:1883": a single-door configuration's startup line is unchanged.
// A door with a name of its own is said with it first, "fleet tcp
// 0.0.0.0:8883 (tls)", which is the only case that can be confused with
// another door of the same kind.
func listening(l config.Listen) []string {
	var out []string
	for _, d := range l.TCP {
		out = append(out, doorLine(d.Name, "tcp", d.Address.Address, d.TLS))
	}
	for _, d := range l.WS {
		out = append(out, doorLine(d.Name, "ws", d.Address.Address, d.TLS))
	}
	for _, d := range l.Unix {
		out = append(out, doorLine(d.Name, "unix", d.Path, nil))
	}
	return out
}

// doorLine is one listener's entry on the startup line.
func doorLine(name, kind, address string, t *config.TLS) string {
	if name == kind {
		return kind + " " + address + encrypted(t)
	}
	return name + " " + kind + " " + address + encrypted(t)
}

// encrypted marks a listener that serves TLS, on the line that says a
// broker is up. Whether a port is encrypted is not something an operator
// should have to work out from which file they edited.
func encrypted(t *config.TLS) string {
	if t == nil {
		return ""
	}
	return " (tls)"
}

// operationsAddresses is where the operations listener answers, for the
// startup line and for a bind that failed. Both come from the operator's
// own file.
func operationsAddresses(l config.OperationsListen) string {
	var out []string
	for _, d := range l.TCP {
		out = append(out, doorLine(d.Name, "tcp", d.Address.Address, d.TLS))
	}
	for _, d := range l.Unix {
		out = append(out, doorLine(d.Name, "unix", d.Path, nil))
	}
	return strings.Join(out, " ")
}

// serverTLS reads a listener's certificate, or returns nil for a listener
// that serves none.
//
// **Read here rather than at the first handshake**, so that a missing file,
// a key that does not match its certificate, or a permission an operator
// meant to fix is a startup error naming the listener - not a client
// somewhere else failing to connect to a broker whose log says it is
// listening. It exits rather than carrying on in plain text: a listener
// configured for TLS and serving without it is the failure that looks like
// success.
//
// **Nothing is defaulted and nothing is generated.** A self-signed
// certificate saguin made would be encryption no client can verify, so
// every client would be told to skip the check - which looks secured, is
// not, and stops anybody asking again.
//
// **What a handshake is served is asked at the handshake**, from a holder
// SIGUSR1 replaces (rereadCertificates). Read once into the config, a renewed
// certificate needed a restart, which drops every connection a broker holds -
// six times a year for a certificate that renews every sixty days.
func serverTLS(t *config.TLS, at string, log *slog.Logger, held *[]*listenerCerts) *tls.Config {
	if t == nil {
		return nil
	}
	pair, pool, err := loadCerts(t)
	if err != nil {
		log.Error("cannot read the TLS certificate", "listener", at, "error", err)
		os.Exit(1)
	}
	l := &listenerCerts{at: at, tls: t}
	l.pair.Store(pair)
	l.pool.Store(pool)
	*held = append(*held, l)
	return l.config()
}

// listenerCerts is one listener's certificate and the authorities it checks a
// client's against, held where SIGUSR1 can replace them while connections
// that were handshaken under the old ones carry on.
type listenerCerts struct {
	at   string
	tls  *config.TLS
	pair atomic.Pointer[tls.Certificate]
	pool atomic.Pointer[x509.CertPool]
}

// config is the listener's tls.Config. Every handshake takes the pair and the
// pool in force at that moment, and nothing else about a listener's TLS
// changes on a re-read: the version floor and whether a certificate is
// required are startup settings.
func (l *listenerCerts) config() *tls.Config {
	min := l.tls.Version()
	current := func() *tls.Config {
		cfg := &tls.Config{Certificates: []tls.Certificate{*l.pair.Load()}, MinVersion: min}
		if pool := l.pool.Load(); pool != nil {
			cfg.ClientCAs = pool
			cfg.ClientAuth = tls.VerifyClientCertIfGiven
			if l.tls.CertificateRequired() {
				cfg.ClientAuth = tls.RequireAndVerifyClientCert
			}
		}
		return cfg
	}
	// **GetConfigForClient alone.** Its answer replaces this config before
	// a certificate is chosen, and tls.Listen and http's ServeTLS both take
	// it as a certificate source, so a GetCertificate here was never called.
	return &tls.Config{
		MinVersion: min,
		GetConfigForClient: func(*tls.ClientHelloInfo) (*tls.Config, error) {
			return current(), nil
		},
	}
}

// loadCerts reads a listener's certificate and key, and its client CA where
// one is named.
//
// Mutual TLS, when an authority is named, is read for the same reason the
// certificate is: an unreadable CA file is an error naming the listener, not
// a fleet that cannot connect to a broker whose log says it is up.
func loadCerts(t *config.TLS) (*tls.Certificate, *x509.CertPool, error) {
	pair, err := tls.LoadX509KeyPair(t.CertFile, t.KeyFile)
	if err != nil {
		return nil, nil, err
	}
	if !t.MutualTLS() {
		return &pair, nil, nil
	}
	pool, err := certPool(t.ClientCAFile)
	if err != nil {
		return nil, nil, fmt.Errorf("the client CA: %w", err)
	}
	return &pair, pool, nil
}

// rereadCertificates re-reads every TLS listener's certificate, key and client
// CA **at the paths the broker started with**, and puts them in force for the
// handshakes that follow. A connection already open keeps the certificate it
// was handshaken with.
//
// **Nothing is applied unless every listener's files load**, which is the
// rule the credential files already keep: a renewal arrives as two files
// written one after the other, so a signal between them meets a certificate
// and a key that do not match - and must leave every listener serving the
// pair it had rather than some of them half-renewed.
func rereadCertificates(log *slog.Logger, held []*listenerCerts) {
	type loaded struct {
		l    *listenerCerts
		pair *tls.Certificate
		pool *x509.CertPool
	}
	next := make([]loaded, 0, len(held))
	failed := false
	for _, l := range held {
		pair, pool, err := loadCerts(l.tls)
		if err != nil {
			log.Error("SIGUSR1: a TLS certificate cannot be used, so no certificate was re-read "+
				"and every listener is serving what it had", "listener", l.at, "error", err)
			failed = true
			continue
		}
		next = append(next, loaded{l, pair, pool})
	}
	if failed {
		return
	}
	for _, n := range next {
		n.l.pair.Store(n.pair)
		n.l.pool.Store(n.pool)
		var notAfter time.Time
		if n.pair.Leaf != nil {
			notAfter = n.pair.Leaf.NotAfter
		}
		clientCA := n.pool != nil
		log.Info("SIGUSR1: a TLS certificate was re-read", "listener", n.l.at,
			"not_after", notAfter, "client_ca", clientCA)
	}
}

// anonymousBesideACL is the sentence for a listener that admits a client
// nothing identifies beside an acl_file (config AnonymousBesideACL).
func anonymousBesideACL(id string) string {
	return "listener " + id + " admits a client with no certificate and no password beside the " +
		"acl_file: its identity is the empty name, which only a `*` pattern matches, so it is " +
		"granted whatever `*` grants"
}

// clientAuthState is what the startup line says about how clients
// authenticate: phrases this file writes, never anything from a file.
//
// **Per door, because the doors can differ.** A listener may name its own
// password_file and allow_anonymous (RFC 0002 "Who may connect"), and this
// line described the broker-wide pair alone: a tcp door with its own file,
// which answered an anonymous CONNECT 0x86, was said to admit every client,
// and RFC 0002's own example - a unix door admitting anonymous beside a fleet
// door that does not - read "password file". This is the question an
// operator most wants confirmed at startup. Where every door says the same
// it is said once, as before; otherwise each door is named.
func clientAuthState(m config.MQTT) string {
	certs, auth := m.ListenerCertificates(), m.ListenerAuth()
	var doors []string
	for _, d := range m.Listen.TCP {
		doors = append(doors, d.Name)
	}
	for _, d := range m.Listen.WS {
		doors = append(doors, d.Name)
	}
	for _, d := range m.Listen.Unix {
		doors = append(doors, d.Name)
	}
	var parts []string
	first, same := "", true
	for _, door := range doors {
		a, ok := auth[door]
		if !ok {
			continue
		}
		file, anonymous := a.Resolve(m)
		phrase := doorAuthState(certs[door], file, anonymous)
		if len(parts) == 0 {
			first = phrase
		} else if phrase != first {
			same = false
		}
		parts = append(parts, door+"="+phrase)
	}
	if same {
		return first
	}
	return strings.Join(parts, " | ")
}

// doorAuthState is one door's phrase: its certificate half first, because on
// a door that requires one no password admits anybody, and "password file"
// alone there would describe a broker somebody else is running.
func doorAuthState(cert, passwordFile string, anonymous bool) string {
	passwords := "no password file"
	switch {
	case passwordFile == "":
	case anonymous:
		passwords = "password file, anonymous also admitted"
	default:
		passwords = "password file"
	}
	switch cert {
	case config.CertRequired:
		return "client certificate required; " + passwords
	case config.CertAccepted:
		return "client certificate accepted; " + passwords
	}
	if passwordFile == "" {
		return "none (every client admitted)"
	}
	return passwords
}

// authenticationState is what the startup line says about /metrics: words
// saguin writes, never anything from a file.
//
// **Per door, because the two can differ.** A deployment may name the
// operators on the port and leave the socket to its file permissions, and
// one word for the pair would be true of one door and a lie about the
// other - on the question an operator most wants confirmed at startup.
//
// **A required client certificate is said**, because it authenticates a
// routable port as a password does: validation admits one on 0.0.0.0 for
// that reason, and "none" there described a door that admits nobody without
// a certificate.
func authenticationState(o *config.Operations) string {
	var parts []string
	for _, d := range o.OperatorFiles() {
		var said []string
		if d.Path != "" {
			said = append(said, "basic")
		}
		if door := o.Listen.TCPNamed(d.Door); door != nil && door.TLS.CertificateRequired() {
			said = append(said, "client certificate")
		}
		state := "none"
		if len(said) > 0 {
			state = strings.Join(said, "+")
		}
		parts = append(parts, d.Door+"="+state)
	}
	if len(parts) == 0 {
		return "none"
	}
	return strings.Join(parts, " ")
}

// usage is the header and the flag list, on whichever stream the caller
// says. Which one that is depends on whether somebody asked for it, which
// is the whole of the reason this takes a writer.
func usage(w io.Writer) {
	fmt.Fprint(w, banner())
	fmt.Fprintln(w, "\nUsage:")
	flag.CommandLine.SetOutput(w)
	flag.PrintDefaults()
}

// writePIDFile writes this process's id, replacing whatever was there.
//
// **Written whole and renamed into place**, so a supervisor reading it never
// sees a half-written number - which it would parse as a different process,
// or as none.
func writePIDFile(path string) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".saguin-pid-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := fmt.Fprintf(tmp, "%d\n", os.Getpid()); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}

// rereadLevel re-reads the configuration file and applies the log level from
// it, leaving every other setting where it was.
//
// It is one of SIGUSR1's four re-reads, beside rereadOrigins,
// rereadCredentials and rereadCertificates; the last two re-read files rather
// than keys.
//
// **It says what it did not do.** Addresses and storage are startup-only,
// so an operator who edited `max_message_size` and sent the
// signal would otherwise be left believing it had been applied - which is
// the shape of a configuration that silently means something other than what
// it says.
//
// **An unreadable or invalid file changes nothing and does not stop the
// broker.** The operator may be mid-edit, and a signal that took a running
// broker down over a half-saved file would be worse than no signal.
//
// It returns the file it loaded, or nil when it could not be used, so that
// everything else SIGUSR1 takes from the configuration file comes from the
// same read: an edit landing between two reads would otherwise apply half of
// one version and half of another.
func rereadLevel(log *slog.Logger, level *slog.LevelVar, path string) *config.File {
	cfg, _, err := config.Load(path)
	if err != nil {
		log.Error("SIGUSR1: the configuration file is not valid, so nothing changed",
			"path", path, "level", level.Level(), "error", err)
		return nil
	}
	was, now := level.Level(), cfg.Broker.Level()
	// **Announced before the switch, and at the stricter of the two levels,
	// so that the line survives whichever direction it moves.** Written
	// after the switch at Info it vanished exactly when it was raised: an
	// operator quietening a log to `warn` got no acknowledgement, and could
	// not tell a signal that took from one that was lost. The stricter
	// level passes both filters - the one in force now, and the one about
	// to be.
	announce := was
	if now > announce {
		announce = now
	}
	log.Log(context.Background(), announce,
		"SIGUSR1: the log level was re-read; addresses and storage are startup-only "+
			"and were not applied",
		"path", path, "was", was.String(), "now", now.String())
	level.Set(now)
	return cfg
}

// rereadOrigins puts each ws door's same_origin and allowed_origins, as cfg
// now reads them, in force together. A door named in the running broker but
// no longer in the file keeps what it had - ports are startup-only - and
// one in the file naming no matching door is silently nothing to apply to.
func rereadOrigins(log *slog.Logger, wsListeners map[string]*listeners.Websocket, cfg *config.File) {
	for _, d := range cfg.Broker.MQTT.Listen.WS {
		ws, ok := wsListeners[d.Name]
		if !ok {
			continue
		}
		origins := d.Origins()
		ws.SetOriginPolicy(listeners.OriginPolicy{SameOrigin: d.SameOriginOn(), Allowed: origins})
		log.Info("SIGUSR1: a ws door's same_origin and allowed_origins were re-read",
			"listener", d.Name, "same_origin", d.SameOriginOn(), "sites", len(origins))
	}
}

// rereadCredentials re-reads the password files and the acl_file **at the
// paths the broker started with**, and puts them in force.
//
// This is the half of SIGUSR1 that is about who may connect and what they
// may do. It exists because the alternative was a lie an operator acts on:
// the files were read once at startup, so withdrawing a credential changed
// nothing until a restart - and a restart of a broker holding durable
// sessions costs every connection and every in-flight record, which is
// precisely what an operator revoking one device is trying not to do.
//
// **The paths come from the startup configuration, not from the file as it
// now reads.** Which file names the credentials is a startup-only setting
// like an address or a certificate; this signal re-reads their *contents*.
// A signal that could also repoint them would be a configuration reload
// wearing a re-read's name, and the first thing it would silently accept is
// an acl_file key deleted by accident - every client granted everything, on
// a signal an operator sent to take a grant away.
//
// **Nothing is applied unless everything loaded**, which is what
// loadAuthorization is for: a signal arrives in the middle of an edit as
// often as after one, and a half-saved file must leave the broker exactly
// as it was rather than half-narrowed.
func rereadCredentials(log *slog.Logger, b *broker.Broker, ops *broker.Operators,
	cfg *config.File, reg *channel.Registry) {

	auth, findings := loadAuthorization(cfg, reg)
	if len(findings) > 0 {
		// **At Error, one line per finding, and saying that nothing
		// changed.** An operator who signalled and got silence would read
		// it as a re-read that worked, which is the failure this whole
		// signal exists to end - one level further in.
		for _, finding := range findings {
			log.Error("SIGUSR1: a credential file cannot be used, so nothing was "+
				"re-read and the broker is running what it had", "finding", finding)
		}
		return
	}
	auth.applyTo(b, ops)
	warnUnnamable(log, auth)

	// **What it now holds, not merely that it happened.** A count is how an
	// operator tells a file that was re-read from one that was re-read
	// empty - the two are the same line otherwise, and only one of them
	// means the fleet is about to be locked out.
	path, af := cfg.Broker.MQTT.PasswordFile, auth.aclPath
	switch {
	case auth.clients != nil && auth.acl != nil:
		log.Info("SIGUSR1: who may connect and what they may do were re-read",
			"password_file", path, "users", len(auth.clients.Users()),
			"acl_file", af, "roles", len(auth.acl.Roles),
			"user_patterns", len(auth.acl.Users))
	case auth.clients != nil:
		log.Info("SIGUSR1: who may connect was re-read; there is no acl_file",
			"password_file", path, "users", len(auth.clients.Users()))
	case auth.acl != nil:
		log.Info("SIGUSR1: what a client may do was re-read; there is no password_file",
			"acl_file", af, "roles", len(auth.acl.Roles),
			"user_patterns", len(auth.acl.Users))
	default:
		// **Only when no listener has one either.** A broker whose doors
		// each name their own file has no broker-wide pair and is not a
		// broker that admits anybody, so saying so here would be false at
		// exactly the deployment most likely to be signalled.
		doorsWithAFileCount := 0
		for _, d := range auth.doors {
			if d.users != nil {
				doorsWithAFileCount++
			}
		}
		if doorsWithAFileCount > 0 {
			log.Info("SIGUSR1: who may connect was re-read from each listener's own "+
				"password_file; there is no acl_file", "listeners", doorsWithAFileCount)
		} else {
			// Worth a line rather than silence: an operator who signalled a
			// broker that authenticates nobody has learnt something.
			log.Info("SIGUSR1: there is no password_file and no acl_file to re-read, " +
				"so every client that can reach a listener may do anything")
		}
	}
	// **A second line for the operations doors**, because they are a
	// different question with a different answer: who may read /metrics is
	// not who may publish, and a deployment often has one file and not the
	// other.
	if o := cfg.Broker.Operations; o != nil {
		for _, d := range o.OperatorFiles() {
			if path = d.Path; path != "" {
				log.Info("SIGUSR1: who may read the operations routes was re-read",
					"key", d.Where, "path", path)
			}
		}
	}
}

func main() {
	cfgPath := flag.String("config", "", "path to the configuration file (required to run a broker)")
	check := flag.Bool("check-config", false,
		"validate a configuration and exit:\n"+
			"  saguin --check-config <config-file>")
	output := flag.Bool("output", false,
		"with --check-config, print the configuration as it resolved - every\n"+
			"  !include expanded and every default filled in - to standard output")
	toSQLite := flag.Bool("snapshots-to-sqlite", false,
		"convert a snapshot directory into a new sqlite database, and exit:\n"+
			"  saguin --snapshots-to-sqlite <snapshot-dir> <database-to-create>")
	toSnapshots := flag.Bool("sqlite-to-snapshots", false,
		"convert a sqlite database into a directory of snapshots, and exit:\n"+
			"  saguin --sqlite-to-snapshots <database> <empty-snapshot-dir>")
	managePasswords := flag.Bool("passwd", false,
		"manage a password file, and exit:\n"+
			"  saguin --passwd list   <file>\n"+
			"  saguin --passwd add    <file> <user> [password]\n"+
			"  saguin --passwd delete <file> <user>\n"+
			"  saguin --passwd scope  <file> <user> <routes>   operators' file only")
	explainACLFlag := flag.Bool("acl", false,
		"explain what a client may do, and exit:\n"+
			"  saguin --acl <config-file> <user-name> [client-id]\n"+
			"  saguin --acl <config-file> < names.txt    one per line, seven columns out")
	routeFlag := flag.Bool("route", false,
		"say where a topic lands or what a filter reaches, and exit:\n"+
			"  saguin --route <config-file> <topic-or-filter>\n"+
			"  saguin --route <config-file> < topics.txt   one per line, four columns out")
	jsonOut := flag.Bool("json", false,
		"with --acl or --route, answer in JSON rather than columns:\n"+
			"  one object per line, compact, no header - pipe it to jq")
	licences := flag.Bool("licenses", false,
		"print the licences of the code inside this binary, and exit")
	showVersion := flag.Bool("version", false,
		"print the version and exit")

	// **A usage message somebody asked for goes to standard output; one
	// provoked by a mistake goes to standard error.** `saguin --help | less`
	// should carry it, and a script watching stderr for a bad flag should
	// see the bad flag.
	//
	// Both halves are written here rather than left to the flag package,
	// because it writes the error line *and* the usage to one stream -
	// whichever `SetOutput` last named. Pointing that at standard output to
	// get `--help` right therefore put `flag provided but not defined` there
	// too, and left stderr empty on a failed run: 1,167 bytes to stdout, 0
	// to stderr, exit 2. So the package is told to print neither, and which
	// stream each half goes to is decided below, where the difference
	// between the two is known.
	flag.CommandLine.Init(os.Args[0], flag.ContinueOnError)
	flag.CommandLine.SetOutput(io.Discard)
	flag.Usage = func() {}

	switch err := flag.CommandLine.Parse(os.Args[1:]); {
	case errors.Is(err, flag.ErrHelp):
		// --help, which is not a failure: nothing is wrong and the exit
		// code says so.
		usage(os.Stdout)
		return
	case err != nil:
		fmt.Fprintln(os.Stderr, err)
		usage(os.Stderr)
		os.Exit(2)
	}

	// Before anything else, including --licenses: the shortest question
	// anybody asks of a binary is which one it is.
	if *showVersion {
		fmt.Print(banner())
		fmt.Printf("build %s\n", version())
		return
	}

	// Before anything is loaded: somebody asking whose code they are running
	// should not have to have a configuration file to find out.
	if *licences {
		fmt.Print(notices)
		os.Exit(0)
	}

	// A migration reads and writes the paths it is given and exits. It is
	// not a broker, so nothing below runs and no configuration is loaded.
	if *toSQLite && *toSnapshots {
		fmt.Fprintln(os.Stderr,
			"--snapshots-to-sqlite and --sqlite-to-snapshots cannot be given together:\n"+
				"a migration goes one way, and which way is the whole of what you are asking for.")
		os.Exit(1)
	}
	if *toSQLite {
		os.Exit(migrateToSQLite(flag.Args(), flagGiven("config"), flagGiven("check-config")))
	}
	if *toSnapshots {
		os.Exit(migrateToSnapshots(flag.Args(), flagGiven("config"), flagGiven("check-config")))
	}
	if *managePasswords {
		os.Exit(managePasswd(flag.Args(), flagGiven("config"), flagGiven("check-config")))
	}

	// Reads the files it is given and prints what they came to. Neither is a
	// broker: nothing below runs and nothing is opened for writing.
	//
	// **Both take the configuration as their first argument and no
	// `--config`**, which is the shape every other exit-early flag here
	// already had - `--passwd` and the two migrations refuse `--config`
	// outright. `--check-config` was the one that did not, and it does now.
	// operands rather than flag.Args(): a flag written after the
	// configuration is still a flag, which the flag package alone does not
	// manage once the configuration is an operand.
	args, argErr := operands()
	if argErr != nil {
		fmt.Fprintln(os.Stderr, argErr)
		usage(os.Stderr)
		os.Exit(2)
	}
	form := asColumns
	if *jsonOut {
		form = asJSON
	}
	if *explainACLFlag {
		os.Exit(explainACL(args, os.Stdin, os.Stdout, os.Stderr, pipedIn(), form))
	}
	if *routeFlag {
		os.Exit(routeTopic(args, os.Stdin, os.Stdout, os.Stderr, pipedIn(), form))
	}

	// **`--check-config <file>`, not `--config <file> --check-config`.** It
	// validates the file it is handed and starts nothing, so it takes its
	// argument the way the other exit-early flags do rather than borrowing
	// the flag that says which broker to run. `--config` alongside is
	// refused with a sentence rather than ignored: an operator who wrote the
	// old form is told, instead of watching a command they thought they knew
	// do something else.
	if *check {
		if flagGiven("config") {
			fmt.Fprintln(os.Stderr, "--config cannot be given with --check-config: it validates "+
				"the file you name and starts nothing.")
			fmt.Fprintln(os.Stderr, "  saguin --check-config <config-file>")
			os.Exit(1)
		}
		if len(args) != 1 {
			fmt.Fprintln(os.Stderr, "usage: saguin --check-config <config-file>")
			fmt.Fprintln(os.Stderr, "  add --output to print the configuration as it resolved")
			os.Exit(1)
		}
		*cfgPath = args[0]
	}

	// No default. A broker that starts from whatever saguin.yaml happens to
	// be in the working directory serves a configuration nobody named - and
	// which one that is depends on where it was started from, so a systemd
	// unit and a shell in the source tree disagree about what the same
	// command means.
	if *cfgPath == "" {
		fmt.Fprintln(os.Stderr, "--config is required: name the configuration file to run, as")
		fmt.Fprintln(os.Stderr, "  saguin --config /etc/saguin/saguin.yaml")
		os.Exit(1)
	}

	// **A LevelVar rather than a level**, because the configuration that
	// names the level has not been read yet and the errors below it must
	// still be logged. It starts at Info, so a broker that never reaches a
	// valid configuration says exactly what it always did.
	level := new(slog.LevelVar)
	log := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: level}))

	cfg, reg, err := config.Load(*cfgPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "configuration is invalid:")
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	// Every file the configuration names, opened before anything is said
	// about the configuration being valid - for --check-config, because RFC
	// 0002 promises a non-zero exit on any finding and an ExecStartPre that
	// passes before a unit dies is worth less than none, and for a real
	// start, because one message naming every unreadable file beats finding
	// them one restart at a time.
	// Set before anything else the broker says, so that a run asking for
	// debug gets it from the first line rather than from wherever the
	// logger happened to be handed over.
	level.Set(cfg.Broker.Level())

	if findings := unopenable(cfg, reg); len(findings) > 0 {
		fmt.Fprintf(os.Stderr, "%s: the configuration names files saguin cannot use:\n", *cfgPath)
		for _, f := range findings {
			fmt.Fprintf(os.Stderr, "  - %s\n", f)
		}
		// The document still goes to standard output when it was asked for.
		// Somebody reading a configuration from a backup on another machine
		// wanted the document, and the findings above are true there rather
		// than merely inconvenient.
		if *check && *output {
			if doc, err := cfg.Flatten(reg); err == nil {
				os.Stdout.Write(doc)
			}
		}
		os.Exit(1)
	}

	if *check {
		// The summary goes to standard error when the document is being
		// printed, and to standard output otherwise. A redirect has to
		// capture the whole of the document and nothing else, or what it
		// captures is not a configuration - and RFC 0004's runbook diffs
		// two of these against each other.
		summary := os.Stdout
		if *output {
			summary = os.Stderr
			doc, err := cfg.Flatten(reg)
			if err != nil {
				fmt.Fprintf(os.Stderr, "cannot write the configuration out: %v\n", err)
				os.Exit(1)
			}
			os.Stdout.Write(doc)
		}
		fmt.Fprintf(summary, "%s: ok\n", *cfgPath)
		for _, id := range cfg.Broker.MQTT.AnonymousBesideACL() {
			fmt.Fprintf(summary, "  warning: %s\n", anonymousBesideACL(id))
		}
		// **Sorted, because this summary is a thing people diff.** It is
		// what an ExecStartPre or a CI step captures, and walked from a map
		// it came out in a different order on successive runs - so two runs
		// over a file nobody touched differed, which is noise where the
		// whole point is to notice a change.
		//
		// By name, which puts a queue's derived `__dlq` directly after it
		// for any ordinary channel name. The routing table `--route` prints
		// is already ordered and `--output` is a stable document; this was
		// the one listing that was not.
		names := make([]string, 0, len(reg.All()))
		for name := range reg.All() {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			fmt.Fprintf(summary, "  %-24s %s\n", name, reg.All()[name].Type)
		}
		// Notes rather than findings, so `ok` above stands and the exit code
		// stays zero: each of these is a configuration that works and may
		// well be meant. What they have in common is that the file does not
		// show the cost, and this is the one place an operator reads a
		// configuration back before deploying it.
		// Where each bridge rule's records go, which is the answer a rule's
		// `channel:` used to make an operator write out and keep in step.
		// Printed always rather than only when something looks wrong: a
		// bridge is the one place a topic is rewritten, so where the
		// rewritten topic lands is worth reading every time.
		for _, n := range bridgeReach(cfg, reg) {
			fmt.Fprintf(summary, "  %s\n", n)
		}
		for _, n := range collapsingRules(cfg, reg) {
			fmt.Fprintf(summary, "  note: %s\n", n)
		}
		return
	}
	// --output is what --check-config prints rather than a thing of its
	// own: a broker that started and also wrote its configuration to
	// standard output would be writing into whatever the unit's stdout is.
	if *output {
		fmt.Fprintln(os.Stderr, "--output prints what --check-config resolved, so it is given with it:")
		fmt.Fprintln(os.Stderr, "  saguin --config /etc/saguin/saguin.yaml --check-config --output")
		os.Exit(1)
	}
	// The same rule for --json: it is how the two inspect commands answer
	// rather than a thing of its own, and a broker that started because a
	// flag was ignored is a broker nobody asked for.
	if *jsonOut {
		fmt.Fprintln(os.Stderr, "--json is how --acl and --route answer, so it is given with one of them:")
		fmt.Fprintln(os.Stderr, "  saguin --acl   /etc/saguin/saguin.yaml device-7 --json")
		fmt.Fprintln(os.Stderr, "  saguin --route /etc/saguin/saguin.yaml iot/depot/state/dev-1 --json")
		os.Exit(1)
	}

	limits := cfg.Broker.Limits.Resolve()
	// From `broker.mqtt` rather than `broker.limits`, and set here because
	// this is where both halves of the configuration are in one hand.
	limits.MinProtocolVersion = cfg.Broker.MQTT.MinProtocol()
	srv, b, err := broker.NewServer(reg, limits, log)
	if err != nil {
		log.Error("cannot build the server", "error", err)
		os.Exit(1)
	}

	// **Who may connect and what they may do, read before any listener
	// opens and read again on SIGUSR1.** Both times through
	// loadAuthorization, so a credential the signal accepts is one the
	// startup would have accepted: two copies of this resolution is how a
	// broker comes to admit somebody a re-read had refused.
	//
	// A hash saguin cannot read is a startup error naming the line rather
	// than a fleet that appears to have forgotten its passwords - which is
	// the whole reason passwd.Load refuses an argon2id entry instead of
	// returning false for it.
	operators := &broker.Operators{}
	auth, findings := loadAuthorization(cfg, reg)
	if len(findings) > 0 {
		for _, finding := range findings {
			log.Error("cannot use a file the configuration names", "finding", finding)
		}
		os.Exit(1)
	}
	auth.applyTo(b, operators)
	warnUnnamable(log, auth)
	if af := auth.aclPath; af != "" {
		log.Info("authorization is on", "path", af,
			"roles", len(auth.acl.Roles), "user_patterns", len(auth.acl.Users))
	}

	// What each door does about client certificates, from the same helper
	// the startup line reads, so the two cannot describe one door two ways.
	// It changes who may connect as completely as a password file does and
	// in a direction the names cannot express: a door requiring one admits
	// whoever the authority signed and refuses every name in the file.
	//
	// **Not re-read on a signal**: whether a door requires a certificate,
	// accepts one or examines none is its configuration, read once, and
	// changing it is a restart. What SIGUSR1 re-reads is the authority's
	// file (rereadCertificates) - the certificates a door checks against,
	// never whether it checks.
	for listenerID, state := range cfg.Broker.MQTT.ListenerCertificates() {
		b.SetListenerCertificates(listenerID, state)
	}

	// The configuration `/v1/operations/config` answers with, resolved once
	// here and never re-read: the file is read at startup and editing it
	// under a running broker changes nothing until the next start, so the
	// document this route serves is what the process is running rather than
	// what is on disk (RFC 0005).
	//
	// **Refused rather than served empty if it cannot be built.** A broker
	// that came up answering an operator's "what are you running" with `{}`
	// is worse than one that did not come up, because the empty answer is
	// believed.
	report, err := cfg.Report(reg)
	if err != nil {
		log.Error("cannot render the configuration for the operations listener", "error", err)
		os.Exit(1)
	}
	b.SetConfigDocument(report)

	// One broker at a time writes a snapshot directory, for the same reason
	// one writes a database - and here the failure is worse. Two brokers
	// hold entirely separate state and both write at shutdown, one file per
	// channel with an atomic rename, so the later one wins: the other's
	// records are gone with nothing reported, and the channel's next offset
	// goes backwards, which hands a stored consumer position records it
	// never saw and lets it report success over them (invariant 9).
	//
	// The lock is a SQLite file even though nothing here is a database.
	// SQLite is what makes it portable, the binary links it regardless, and
	// a memory provider has no file of its own to take the lock with.
	dirs := map[string]*store.Dir{}
	var dirLocks []*sqlite.Lock
	retainedProvider, retainedPeriod := cfg.RetainedStore()
	qos2MaxInflight, qos2Expires := cfg.QoS2Limits()
	sessionProvider := cfg.SessionStore()
	used := inUse(reg, retainedProvider, sessionProvider)
	for provider, path := range cfg.Broker.Storage.SnapshotDirs() {
		// A provider no channel names gets no directory and no lock, the
		// same as a database nothing names.
		if !used[provider] {
			log.Info("storage declared and unused: nothing is created for it",
				"provider", provider, "type", "memory", "snapshot_dir", path)
			continue
		}
		// Made here rather than at the shutdown that writes into it. The
		// mode is the one Save uses, and a directory that cannot be created
		// is worth learning about now: found at shutdown, it is found by
		// losing the snapshot it was going to hold.
		err := os.MkdirAll(path, 0o700)
		var lock *sqlite.Lock
		if err == nil {
			lock, err = sqlite.Hold(filepath.Join(path, snapshotLockName), path)
		}
		if err != nil {
			log.Error("cannot open a storage provider", "provider", provider, "error", err)
			for _, l := range dirLocks {
				_ = l.Release()
			}
			os.Exit(1)
		}
		dirLocks = append(dirLocks, lock)
		dirs[provider] = store.NewDir(path, version())
	}
	defer func() {
		for _, l := range dirLocks {
			if err := l.Release(); err != nil {
				log.Error("cannot release a snapshot directory lock", "error", err)
			}
		}
	}()
	b.SetSnapshotDirs(dirs)

	// A memory provider has no engine to bound it, so the counting is
	// saguin's and it spans the provider's channels: what is being
	// protected is one machine's memory rather than one channel's growth.
	quotas := map[string]*store.Quota{}
	memReserve := cfg.Broker.Limits.StorageReserve()
	bounds := cfg.Broker.Storage.MaxBytes()
	var declaredBytes, boundedProviders int64
	// **Every memory provider gets one, bounded or not.** A quota with no
	// maximum counts and never refuses - Take's guard is `max > 0` - and
	// counting is the point: saguin_provider_bytes is "bytes the provider
	// holds", and building a quota only where there was something to enforce
	// left an unbounded provider reporting zero whatever it held. The sqlite half of the same defect had the same shape.
	for provider, p := range cfg.Broker.Storage.Providers {
		if p.Type != "memory" {
			continue
		}
		n := bounds[provider]
		q := store.NewQuota(n, memReserve)
		quotas[provider] = q
		if n == 0 {
			continue
		}
		boundedProviders++
		declaredBytes += n
		publish, full := q.Effective()
		log.Info("storage bounded", "provider", provider, "type", "memory", "max_bytes", n,
			"publishes_stop_at", publish, "reserved_for_relief", full-publish)
	}
	// **The one thing splitting providers across files cannot be refused
	// for.** Two names on one path are two writers on one store and are a
	// startup error; two sub-operators each declaring 8GiB of memory on a
	// 2GB box is not a clash - every provider is separately reasonable and
	// only the sum is not. saguin cannot know what the machine has, so it
	// states the total it was asked for, in the one place somebody is
	// looking, and leaves the arithmetic to whoever owns the box.
	// The providers that declared a bound, not the ones that have a quota:
	// every memory provider has one now, and a total over providers that
	// declared nothing would be a sum of zeroes reported as an estate's
	// memory budget.
	if boundedProviders > 1 {
		log.Info("memory storage declared", "providers", boundedProviders, "max_bytes", declaredBytes)
	}
	b.SetQuotas(quotas)

	// Opened before any listener, like the snapshots below: a database
	// that will not open stops the broker here rather than after a client
	// has published into a channel that turns out to have nowhere to go.
	databases, err := openDatabases(cfg, reg, b, log)
	if err != nil {
		log.Error("cannot open a storage provider", "error", err)
		os.Exit(1)
	}
	defer func() {
		for provider, db := range databases {
			if err := db.Close(); err != nil {
				log.Error("closing a storage provider", "provider", provider, "error", err)
			}
		}
	}()

	// What answers saguin_provider_bytes and saguin_provider_max_bytes: the
	// quota for a memory provider, the database itself for a sqlite one.
	//
	// **Here rather than beside SetQuotas**, because a sqlite provider
	// cannot say how large its file is until the file is open. Registering
	// both kinds in one place is also the point: the collector asks a
	// provider what it holds instead of knowing how each kind is bounded,
	// which is what let a bounded database report that it had no bound.
	measures := make(map[string]broker.ProviderMeasure, len(quotas)+len(databases))
	for provider, q := range quotas {
		measures[provider] = q
	}
	for provider, db := range databases {
		measures[provider] = db
	}
	b.SetProviderMeasures(measures)

	// The retained store, where a retained message on a broadcast topic is
	// kept (RFC 0002 "Retained messages on a broadcast topic"). Always
	// attached: the block only moves it off broker.storage.default or gives
	// it a period, and refusing retained values is the acl_file's per-client
	// denial.
	//
	// After the databases are open, because a sqlite provider holds it in a
	// table the way it holds a latest channel, and before the snapshots are
	// loaded, because a memory provider's copy of it is in one of those
	// files.
	var lt broker.LatestStore
	if db := databases[retainedProvider]; db != nil {
		lt, err = db.Latest(broker.RetainedStoreName)
		if err != nil {
			log.Error("cannot open the retained store", "provider", retainedProvider, "error", err)
			os.Exit(1)
		}
	} else {
		// A memory provider. What it survives is the snapshot below and
		// nothing else, which is what a memory provider promises for
		// every channel on it too (invariant 14).
		lt = store.NewLatest()
	}
	b.SetRetained(retainedProvider, lt, retainedPeriod)
	// Two lines rather than one with a phrase built into it. What zero
	// means here is not obvious from the number - it is `none`, not
	// "discarded at once" - so each case says it in words.
	if retainedPeriod > 0 {
		log.Info("retained messages on broadcast topics are kept until their topic goes quiet",
			"provider", retainedProvider, "retention_period_s", retainedPeriod)
	} else {
		log.Info("retained messages on broadcast topics are kept until replaced or deleted",
			"provider", retainedProvider, "retention_period", "none")
	}

	// Exactly-once is offered by every broker (RFC 0002 `broker.qos2`): the
	// block only changes the allowance and the expiry, and refusing QoS 2 is
	// the acl_file's per-client denial. A held publish waits in the store of
	// the channel it is for, or the broadcast log's for a broadcast, so there
	// is no store to attach here.
	b.SetQoS2(qos2MaxInflight, qos2Expires)
	log.Info("exactly-once publishing is offered",
		"max_inflight_per_client", qos2MaxInflight,
		"expires_after", qos2Expires)

	// Loaded before any listener opens, so no client can publish into a
	// channel that is about to be replaced by its snapshot. A snapshot
	// that will not load stops the broker here: starting empty is
	// indistinguishable from a fresh install and destroys the evidence
	// (invariant 14).
	//
	// **And before the sessions are read**, so that stopping here ends
	// nothing. The start ends the sessions no client can have any more and
	// publishes the Wills that ending owes once the channels are loaded
	// (PublishDueWills); loaded after that ending, a snapshot this start
	// refused had already ended sessions whose Wills it never published.
	warnings, err := b.LoadSnapshots()
	if err != nil {
		log.Error("cannot load a snapshot", "error", err)
		os.Exit(1)
	}
	for _, w := range warnings {
		log.Warn("snapshot", "finding", w)
	}
	// Where every session's state is kept (RFC 0002 `broker.session`):
	// always attached, on broker.storage.default unless the block names
	// another provider. A sqlite provider keeps it across a crash, a memory
	// one inside its max_bytes.
	var sessions broker.SessionStore
	if db := databases[sessionProvider]; db != nil {
		sessions, err = db.Sessions()
		if err != nil {
			log.Error("cannot open the session store", "provider", sessionProvider, "error", err)
			os.Exit(1)
		}
	} else {
		sessions = store.NewSessions()
		// A memory provider's sessions survive exactly what its channels
		// survive: the file written at the last graceful shutdown, and
		// nothing else (invariant 14). Read here, before the store is
		// attached, because a file comes back as a store rather than being
		// poured into one - the order a session's messages were held in is
		// part of what is restored, and so is where the next one goes.
		//
		// A file that is there and cannot be read stops the broker. Starting
		// with no sessions is indistinguishable from a fresh install, and it
		// is a fleet that reconnects to Session Present 0 with nothing to say
		// why.
		if dir := dirs[sessionProvider]; dir != nil {
			snap, err := dir.LoadSessions()
			if err != nil {
				log.Error("cannot read the sessions left by the last shutdown",
					"provider", sessionProvider, "error", err)
				os.Exit(1)
			}
			if snap != nil {
				sessions = store.RestoreSessions(snap)
				log.Info("sessions read from the last shutdown",
					"provider", sessionProvider, "sessions", len(snap.Sessions),
					"written_at", snap.WrittenAt, "written_by", snap.Writer)
			}
		}
	}
	b.SetSessions(sessionProvider, sessions)
	// A memory provider whose snapshots came back over a bound the operator
	// lowered holds them all and refuses every publish until retention or
	// consumers free room: said once, here, as a sqlite provider over its
	// bound is said where it is opened.
	//
	// **Asked once the sessions are charged, not before**: a session is
	// charged the memory it holds (RFC 0002 "Every session's state:
	// `broker.session`"), so sessions can be what fills the provider. Asked
	// before, such a start said nothing, and then refused every publish to
	// the provider, every SUBSCRIBE and every resume carrying a Will. Where
	// the sessions hold any of it, retention frees none of that: they go when
	// they expire, so the line says what is refused and what to change.
	for provider, q := range quotas {
		if !q.OverBound() {
			continue
		}
		var sessionBytes int64
		if m, ok := sessions.(interface{ Bytes() int64 }); ok && provider == sessionProvider {
			sessionBytes = m.Bytes()
		}
		if sessionBytes > 0 {
			log.Warn("storage already holds more than its max_bytes, sessions among it: publishes to it, "+
				"SUBSCRIBEs and resumes carrying a Will are refused until retention frees room or sessions expire; "+
				"raise max_bytes, or keep sessions on a sqlite provider (broker.session.storage)",
				"provider", provider, "type", "memory", "bytes", q.Bytes(), "max_bytes", q.MaxBytes(),
				"session_bytes", sessionBytes)
			continue
		}
		log.Warn("storage already holds more than its max_bytes: publishes are refused until it is trimmed",
			"provider", provider, "type", "memory", "bytes", q.Bytes(), "max_bytes", q.MaxBytes())
	}
	b.SetAckCommitInterval(cfg.AckCommitInterval())
	interval := b.AckCommitInterval() // what the broker holds, not what was asked
	log.Info("sessions are kept", "provider", sessionProvider, "ack_commit_interval", interval)
	// **What each session is owed from the broadcast log, counted again**,
	// before any listener opens: every durable session's owed list and every
	// message's count are kept in memory only (RFC 0003 "Broadcast"). A log
	// that cannot be read stops the broker, as a sessions file does: a
	// drain started without its lists would owe every session nothing.
	if err := b.StartBroadcast(sessions); err != nil {
		log.Error("cannot count what sessions are owed from the broadcast log",
			"provider", sessionProvider, "error", err)
		os.Exit(1)
	}

	// What a shared group is owed is the broadcast log behind its cursor,
	// started above, and waits at most broker.share.expires_after.
	b.SetShareExpiry(cfg.ShareExpiry())
	log.Info("what shared groups are owed is kept", "provider", sessionProvider,
		"expires_after", b.ShareExpiry())
	// Sessions no client can have any more - expired while the broker was
	// stopped, or ended with a connection the stop cut - are ended here,
	// before any client can connect: nothing else would remove them.
	if expiredCount, endedCount, err := b.DropSessionsLeftByAStop(time.Now()); err != nil {
		log.Error("cannot end the sessions left from before this start", "provider", sessionProvider, "error", err)
		os.Exit(1)
	} else if expiredCount+endedCount > 0 {
		log.Info("ended the sessions left from before this start",
			"provider", sessionProvider, "expired_while_stopped", expiredCount, "ended_with_their_connection", endedCount)
	}
	// And the sessions a client can still have are put back, before any
	// listener opens: each becomes a session this broker holds and nothing is
	// connected to, so the client that comes back is answered Session Present
	// 1 and sent what it was owed.
	if restoredCount, err := b.RestoreSessions(); err != nil {
		log.Error("cannot restore the sessions left from before this start",
			"provider", sessionProvider, "error", err)
		os.Exit(1)
	} else if restoredCount > 0 {
		log.Info("restored the sessions left from before this start",
			"provider", sessionProvider, "sessions", restoredCount)
	}

	// **And what shared groups held past broker.share.expires_after**, gone
	// before any listener opens, as the two above.
	if deliveryCount := b.DropShareBacklogsLeftByAStop(time.Now()); deliveryCount > 0 {
		log.Info("dropped what shared groups held past their expiry before this start",
			"provider", sessionProvider, "deliveries", deliveryCount)
	}

	// The Wills this start found already owed: a device whose delay ran out,
	// or whose session expired, while the broker was stopped. After the
	// snapshots because a Will becomes a record in whatever channel claims
	// its topic, and a record written before that channel's snapshot loads is
	// one the load replaces; before any listener opens, because a subscriber
	// connecting first would be served a death announcement from before the
	// restart as though it had just happened.
	if n := b.PublishDueWills(); n > 0 {
		log.Info("published the Wills this start found owed", "wills", n)
	}

	// After the snapshots, because a topic that has to move may have just
	// come back from one, and before any listener opens, because this is
	// the only moment nothing is publishing into either store.
	if err := b.SettleRetained(); err != nil {
		log.Error("cannot settle the retained store against the configured channels", "error", err)
		os.Exit(1)
	}
	// And the other direction, which nothing else can see: values a filter
	// change has left behind in a channel that no longer matches their
	// topics. Reachable by nobody, reported as absent, and lost to the
	// operator without this line. After SettleRetained, so a value that has
	// just been moved *in* is counted against the filter that claimed it.
	b.CountStranded()

	if !b.Durable() {
		// Invariant 14: no log line may imply a durability saguin does not
		// have, and silence about it is the same thing.
		log.Warn("no storage provider keeps anything: every channel is discarded at shutdown",
			"fix", "under broker.storage.providers, give a memory provider a snapshot_dir "+
				"(kept across a graceful shutdown) or use type: sqlite with a file_path (kept across a crash)")
	}

	// Every TLS listener's certificates, held so SIGUSR1 can replace them.
	var certs []*listenerCerts
	// **The door's name is the listener's ID**, which is what the substrate
	// puts on a connection as `cl.Net.Listener` and what
	// SetListenerCredentials and SetListenerCertificates key on - so a
	// second door of a kind is a second entry everywhere auth already
	// looks a door up by id, with nothing new to teach it.
	for _, d := range cfg.Broker.MQTT.Listen.TCP {
		if err := srv.AddListener(listeners.NewTCP(listeners.Config{
			ID: d.Name, Address: d.Address.Address,
			TLSConfig:   serverTLS(d.TLS, config.DoorPath("tcp", d.Name), log, &certs),
			ConnectRate: cfg.Broker.Limits.Resolve().MaxConnectRate,
		})); err != nil {
			log.Error("cannot listen", "tcp", d.Address.Address, "error", err)
			os.Exit(1)
		}
	}

	// Held past startup, by name, so that SIGUSR1 can replace each door's
	// allowed_origins.
	wsListeners := map[string]*listeners.Websocket{}
	for _, d := range cfg.Broker.MQTT.Listen.WS {
		ws := listeners.NewWebsocket(listeners.Config{
			ID: d.Name, Address: d.Address.Address,
			TLSConfig:   serverTLS(d.TLS, config.DoorPath("ws", d.Name), log, &certs),
			ConnectRate: cfg.Broker.Limits.Resolve().MaxConnectRate,
		})
		ws.SetOriginPolicy(listeners.OriginPolicy{SameOrigin: d.SameOriginOn(), Allowed: d.Origins()})
		ws.SetLogBound(cfg.Broker.Limits.Resolve().Loggable)
		if err := srv.AddListener(ws); err != nil {
			log.Error("cannot listen", "ws", d.Address.Address, "error", err)
			os.Exit(1)
		}
		wsListeners[d.Name] = ws
	}

	for _, d := range cfg.Broker.MQTT.Listen.Unix {
		path := d.Path
		// A socket left behind by a broker that did not stop cleanly is
		// replaced when the listener binds, and one another saguin is serving
		// is refused: listeners.ListenUnix, beside a lock the kernel releases
		// with the process that held it.
		rate := cfg.Broker.Limits.Resolve().MaxConnectRate
		// The socket is the access control: whoever can open the file can
		// speak MQTT to the broker. Its mode is set where it is created
		// (listeners.ListenUnix), for both doors: that is also the one place
		// that knows an abstract name, "@...", has no file to set it on.
		var unixListener listeners.Listener = listeners.NewUnixSock(listeners.Config{
			ID: d.Name, Address: path, ConnectRate: rate, FileMode: d.FileMode(),
		})
		if d.ProxyProtocol {
			proxied := proxyproto.NewUnixSock(d.Name, path, d.FileMode())
			proxied.SetConnectRate(rate)
			unixListener = proxied
		}
		if err := srv.AddListener(unixListener); err != nil {
			log.Error("cannot listen", "unix", path, "error", err)
			os.Exit(1)
		}
		// The socket is removed by its listener's Close at shutdown, under its
		// lock, so it can only ever remove its own.
	}

	// **Handled from before anything answers**: the operations listener
	// below serves as soon as it is bound, and the MQTT listeners after the
	// pid file. A signal that arrives meanwhile waits for the loop at the
	// end of main rather than meeting its default disposition, which for
	// all four is to end the process with no shutdown and no snapshot.
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM, syscall.SIGUSR1, syscall.SIGHUP)
	// **SIGUSR1 re-reads the log level, the ws listener's same_origin and
	// allowed_origins, the credential files, and the TLS certificates and
	// client authorities**, which are the settings whose change is worth
	// having without a restart - and for
	// one reason: a restart of a broker holding durable sessions costs every
	// connection and every in-flight record. Getting `debug` out of a
	// misbehaving bridge is not worth that, and neither is withdrawing one
	// device's password.
	//
	// **The credential half is not a convenience.** Read once at startup, an
	// edited password file or acl_file changed nothing for a running broker,
	// so an operator revoking access had a document telling them to hang the
	// client up - which ends one connection and re-admits it on the next,
	// with every grant it had. That is an authorization failure reporting
	// success, and this is the half that makes it true: re-read, then hang
	// up, and the device is refused when it comes back.
	//
	// **HUP is caught and does nothing, which is not the same as leaving it
	// alone.** nginx's split is USR1 to reopen logs and HUP to reload the
	// configuration; saguin puts everything it can re-read on USR1 and has
	// no configuration reload, so HUP has nothing to do - but an
	// unhandled HUP is not inert, it terminates the process, and it does it
	// the way a `kill -9` would: no shutdown, no snapshot, no pid file
	// removed. A memory-backed channel loses every record acknowledged since
	// its last snapshot, which is data this broker said RC:0 to.
	//
	// That is reachable by accident twice over. mosquitto reloads its
	// configuration on HUP, and the README courts operators migrating from
	// it; and a terminal closing sends HUP to a broker started by hand. The
	// line it writes is Warn rather than Info because the operator asked for
	// something and did not get it - a silent no-op reads exactly like a
	// reload that worked.
	// The operations listener binds with the MQTT listeners rather than
	// after Serve, so a port already in use is a startup error naming it
	// (RFC 0005). It answers as soon as it is bound, which is correct:
	// snapshots are already loaded by this point, so a broker that is
	// listening is a broker that is ready.
	// The two labels the broker cannot work out for itself, and which
	// provider is memory and which is sqlite, all before anything is served.
	b.SetIdentity(cfg.Broker.ID, version())
	b.SetProviderKinds(cfg.Broker.Storage.Kinds())

	if o := cfg.Broker.Operations; o != nil {
		where := operationsAddresses(o.Listen)

		// Loaded before the listener opens, so that a file with a hash
		// saguin cannot read is a startup error naming the line rather than
		// an operator who cannot authenticate against a broker that is
		// otherwise running. That distinction is the whole reason Load
		// refuses an argon2id hash instead of returning false for it.
		//
		// **Each distinct path once, and the resolution is not repeated
		// here.** The two doors may name different files and either may
		// take broker.operations.password_file, so a deployment writes up
		// to three paths with as few as one file behind them.
		// OperatorFiles answers which file each door ends up with, and it
		// is the same call --check-config makes: two copies of that
		// resolution is how --check-config comes to pass a configuration
		// the broker refuses.
		// Who may read these routes was loaded with every other credential
		// file, above - one read, one set of findings, and one thing for
		// SIGUSR1 to replace.

		opsCerts := map[string]*tls.Config{}
		for _, d := range o.Listen.TCP {
			opsCerts[d.Name] = serverTLS(d.TLS, config.OpsDoorPath("tcp", d.Name), log, &certs)
		}
		stopOps, err := b.ServeOperations(o.Listen, o.ScrapeInterval(), operators, opsCerts)
		if err != nil {
			log.Error("cannot listen", "operations", where, "error", err)
			os.Exit(1)
		}
		defer stopOps()
		// The paths, because an operator copying this line into a scrape
		// configuration needs the one that is not /health, and the /v1
		// routes sit behind the same credential. And every address,
		// because a deployment with a socket for its agent and a port for
		// a human has two answers to "where do I curl".
		// Whether /metrics is behind a credential is the first thing an
		// operator wants confirmed and the last thing they want to infer
		// from silence, so the startup line says it either way.
		log.Info("operations listening", "address", where,
			"paths", "/health /metrics /v1/operations/", "min_scrape_interval", o.ScrapeInterval(),
			"metrics_authentication", authenticationState(o))
	}

	// **Written once every listener is bound and the signals are handled,
	// and before anything is served**, and each part of that matters.
	//
	// A supervisor takes this file as "the process is up", so writing it
	// beside a listener that then failed to bind hands out a pid for a
	// process on its way to exiting. And writing it before signal.Notify
	// hands out a pid the moment before the handlers exist: SIGUSR1's
	// default disposition is to terminate, so a supervisor that read the
	// file and immediately asked for debug would kill the broker. Measured
	// - a test that raced those two saw exactly that.
	//
	// **The handlers are installed before anything answers, and this file
	// is written before the MQTT listeners serve**. Installed after the listeners served and after "saguin
	// listening", a signal in the window between - measured at up to 1.2ms,
	// growing with the queues configured - met the default disposition: no
	// shutdown, no snapshot. And a pid file that cannot be written now stops
	// the broker before it has accepted anybody.
	if path := strings.TrimSpace(cfg.Broker.PIDFile); path != "" {
		if err := writePIDFile(path); err != nil {
			// **Exit rather than carry on unmanaged.** An operator who asked
			// for a pid file has something that reads it, and a broker
			// running with nothing to find it is worse than one that did not
			// start: the supervisor believes it failed and starts a second.
			log.Error("cannot write the pid file", "path", path, "error", err)
			os.Exit(1)
		}
		defer func() {
			if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
				log.Warn("cannot remove the pid file", "path", path, "error", err)
			}
		}()
		log.Info("pid file written", "path", path, "pid", os.Getpid())
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	go b.Run(ctx)

	go func() {
		if err := srv.Serve(); err != nil {
			log.Error("server stopped", "error", err)
			os.Exit(1)
		}
	}()

	// Bridges start after the listeners, because a bridge publishes into the
	// same channels a local client does and there is no reason for one to be
	// accepting records while the other cannot. They stop before the
	// snapshot, below, for the reason that matters more: a bridge still
	// carrying records while the state is being read would have them
	// acknowledged upstream and then lost with the process.
	bridges := make([]*bridge.Bridge, 0, len(cfg.BridgeSet()))
	for _, bc := range cfg.BridgeSet() {
		// One client per bridge, and it is both halves: what an inbound
		// rule publishes through and what an outbound rule reads from.
		// Reading and writing under one identity is what makes the bridge's
		// own records recognisable to itself.
		link := b.NewBridgeClient(bc.Name)
		bridges = append(bridges, bridge.New(bc, link, limits, log, link))
	}
	// What the catalogue reports about each one. Handed over as an
	// interface, so internal/broker needs no import of internal/bridge for
	// four numbers.
	stats := make([]broker.BridgeStats, 0, len(bridges))
	for _, br := range bridges {
		stats = append(stats, br)
	}
	b.SetBridges(stats)

	bridgesDone := make(chan struct{})
	if len(bridges) == 0 {
		close(bridgesDone)
	} else {
		go func() {
			defer close(bridgesDone)
			if err := bridge.Set(ctx, bridges); err != nil {
				log.Error("a bridge stopped", "error", err)
			}
		}()
	}

	names := make([]string, 0, len(reg.All()))
	for n := range reg.All() {
		names = append(names, n)
	}
	// Whether clients authenticate is the first thing an operator wants
	// confirmed and the last thing they should infer from silence, so the
	// line that says a broker is up says which of the two it is.
	log.Info("saguin listening",
		"version", version(),
		"broker", cfg.Broker.ID, "listeners", listening(cfg.Broker.MQTT.Listen),
		"protocols", broker.AdmittedProtocols(srv),
		"client_authentication", clientAuthState(cfg.Broker.MQTT),
		"channels", names)
	for _, door := range cfg.Broker.MQTT.AnonymousBesideACL() {
		log.Warn(anonymousBesideACL(door), "listener", door)
	}
	if len(bridges) > 0 {
		// Said at startup rather than left to the first connection log,
		// because a bridge that never reaches its upstream is otherwise
		// indistinguishable from one nobody configured.
		log.Info("bridges starting", "bridges", bridge.Names(bridges))
	}
	for name, c := range reg.All() {
		if c.Type == channel.Queue {
			// The backoff is on this line because it is the one place an
			// operator is told what a queue's retry policy is, and its whole
			// effect is a gap they would otherwise have to time with a
			// stopwatch to discover. `none` is stated rather than omitted:
			// the two ways of writing nothing must not look the same as a
			// broker that ignored the key.
			log.Info("queue ready",
				"channel", name, "subscribe", c.QueueFilter(),
				"respond", c.ResponseTopic(),
				"visibility_timeout_s", c.VisibilityTimeout, "max_attempts", c.MaxAttempts,
				"backoff", backoffName(c.Backoff), "backoff_base_s", c.BackoffBase)
		}
	}

	for {
		switch <-sig {
		case syscall.SIGUSR1:
			if now := rereadLevel(log, level, *cfgPath); now != nil {
				rereadOrigins(log, wsListeners, now)
			}
			rereadCredentials(log, b, operators, cfg, reg)
			rereadCertificates(log, certs)
			continue
		case syscall.SIGHUP:
			log.Warn("SIGHUP does nothing: saguin has no configuration reload. " +
				"SIGUSR1 re-reads broker.log_level, the ws listener's same_origin and allowed_origins, " +
				"the password files and acl_file, and the TLS certificates and client CAs the broker started with; every " +
				"other setting is startup-only and needs a restart")
			continue
		}
		break
	}

	log.Info("shutting down")
	cancel()

	// Before Close, and before the snapshot. A bridge that was still
	// carrying records would have them acknowledged upstream and then lost
	// with the process - acknowledged and lost, one hop further out than
	// saguin can otherwise produce it.
	<-bridgesDone
	if len(bridges) > 0 {
		log.Info("bridges stopped", "bridges", bridge.Names(bridges))
	}

	// Closing the server, waiting for the retention sweeps to finish, and
	// writing the snapshot, in that order and for the reasons at Shutdown.
	// The order is there rather than here so that it can be tested: three
	// statements in this function are three statements anybody can reorder,
	// and the one that matters is invisible until a snapshot is written
	// while a sweep is deleting from the channel being read.
	//
	// Memory durability is exactly that snapshot, so a failure here loses
	// everything the broker held and is an error exit rather than a log
	// line somebody scrolls past.
	if err := b.Shutdown(); err != nil {
		log.Error("the snapshot failed: this broker's memory channels are lost", "error", err)
		os.Exit(1)
	}
	if b.Durable() {
		log.Info("snapshot written")
	}
}

// backoffName is what the startup line calls a queue's retry backoff.
//
// It is here rather than a String method on the type because the store is
// where that type lives and a store has no opinion about how an operator
// reads it. The default prints as "none" rather than as a number, which is
// the same choice every other line here makes about a policy nobody set.
func backoffName(k store.BackoffKind) string {
	switch k {
	case store.BackoffLinear:
		return "linear"
	case store.BackoffExponential:
		return "exponential"
	default:
		return "none"
	}
}
